# Generated by Django 2.1.1 on 2018-09-28 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=32)),
                ('lastseen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Client_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('setting', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Client')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField()),
                ('callid', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='DataIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliententrytime', models.DateTimeField()),
                ('workload', models.CharField(max_length=255)),
                ('direction', models.BooleanField()),
                ('callid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Client')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('setting', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
                ('pattern', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('front_name', models.CharField(max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Helper_Datatype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Helper_Inputtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Orga_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addr_street', models.CharField(max_length=30)),
                ('addr_nr', models.CharField(max_length=5)),
                ('addr_plz', models.CharField(max_length=10)),
                ('addr_city', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Orga_Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('optaname', models.TextField(max_length=75)),
                ('inheritalarm', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Orga_Location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Orga_Units')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Orga_Vehical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('optaname', models.CharField(max_length=30)),
                ('numberplate', models.TextField(max_length=30)),
                ('fmskennung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Data')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.DecimalField(decimal_places=2, max_digits=3)),
                ('builddate', models.DateField()),
                ('creator', models.CharField(max_length=30)),
                ('needsinternet', models.BooleanField(default=0)),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
                ('possibledatatypes', models.ManyToManyField(blank=True, to='bw3backend.Helper_Datatype')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Plugin_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('setting', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('inputtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Plugin')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=1)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Plugin')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PluginInstance_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('plugininstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.PluginInstance')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='PluginInstance_Config_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('setting', models.CharField(max_length=100, unique=True)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('inputtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Plugin')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='plugininstance_config',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.PluginInstance_Config_Template'),
        ),
        migrations.AddField(
            model_name='orga_units',
            name='vehicals',
            field=models.ManyToManyField(blank=True, to='bw3backend.Orga_Vehical'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='inputtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.GlobalConfig_Section'),
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Datatype'),
        ),
        migrations.AddField(
            model_name='client_config',
            name='inputtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype'),
        ),
    ]
