# Generated by Django 2.1.1 on 2018-09-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw3backend', '0003_auto_20180918_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='workload',
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='set_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='set_callbychild',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='set_calldirect',
            field=models.BooleanField(default=1),
        ),
    ]
