# Generated by Django 2.1.1 on 2018-09-20 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bw3backend', '0005_auto_20180918_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataincoming',
            name='type',
        ),
        migrations.RemoveField(
            model_name='orga_vehical',
            name='location',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='set_active',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='set_callbychild',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='set_calldirect',
        ),
        migrations.AddField(
            model_name='client',
            name='lastseen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_config',
            name='front_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='client_config',
            name='front_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orga_units',
            name='inheritalarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='front_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plugin',
            name='front_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plugin',
            name='needsinternet',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='plugin',
            name='possibledatatypes',
            field=models.ManyToManyField(blank=True, null=True, to='bw3backend.helper_datatype'),
        ),
        migrations.AddField(
            model_name='plugin_config',
            name='front_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plugin_config',
            name='front_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='front_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orga_location',
            name='addr_nr',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='orga_location',
            name='addr_plz',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orga_vehical',
            name='numberplate',
            field=models.TextField(max_length=30),
        ),
    ]
