# Generated by Django 2.1.1 on 2018-09-28 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bw3backend', '0006_auto_20180920_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('front_name', models.CharField(max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Helper_Inputtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='PluginInstance_Config_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, unique=True)),
                ('setting', models.CharField(max_length=100, unique=True)),
                ('defaultvalue', models.CharField(blank=True, max_length=255)),
                ('front_name', models.CharField(blank=True, max_length=50)),
                ('front_description', models.TextField(blank=True, max_length=500)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('inputtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.RemoveField(
            model_name='plugininstance_config',
            name='setting',
        ),
        migrations.AddField(
            model_name='client_config',
            name='order',
            field=models.IntegerField(default=100, unique=True),
        ),
        migrations.AddField(
            model_name='client_config',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='front_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='front_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='order',
            field=models.IntegerField(default=100, unique=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plugin_config',
            name='order',
            field=models.IntegerField(default=100, unique=True),
        ),
        migrations.AddField(
            model_name='plugin_config',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client_config',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Client'),
        ),
        migrations.AlterField(
            model_name='client_config',
            name='front_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client_config',
            name='setting',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client_config',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Datatype'),
        ),
        migrations.AlterField(
            model_name='dataincoming',
            name='callid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Data'),
        ),
        migrations.AlterField(
            model_name='dataincoming',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Client'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='setting',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orga_units',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Orga_Location'),
        ),
        migrations.AlterField(
            model_name='orga_units',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Orga_Units'),
        ),
        migrations.AlterField(
            model_name='orga_units',
            name='vehicals',
            field=models.ManyToManyField(blank=True, null=True, to='bw3backend.Orga_Vehical'),
        ),
        migrations.AlterField(
            model_name='orga_vehical',
            name='fmskennung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Data'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='possibledatatypes',
            field=models.ManyToManyField(blank=True, null=True, to='bw3backend.Helper_Datatype'),
        ),
        migrations.AlterField(
            model_name='plugin_config',
            name='front_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plugin_config',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Plugin'),
        ),
        migrations.AlterField(
            model_name='plugin_config',
            name='setting',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plugin_config',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Plugin'),
        ),
        migrations.AlterField(
            model_name='plugininstance_config',
            name='plugininstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.PluginInstance'),
        ),
        migrations.AddField(
            model_name='plugininstance_config_template',
            name='plugininstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.PluginInstance'),
        ),
        migrations.AddField(
            model_name='client_config',
            name='inputtype',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='inputtype',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='section',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.GlobalConfig_Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin_config',
            name='inputtype',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.Helper_Inputtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugininstance_config',
            name='template',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='bw3backend.PluginInstance_Config_Template'),
            preserve_default=False,
        ),
    ]
