# Generated by Django 2.1.1 on 2018-09-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw3backend', '0002_auto_20180918_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
