# Generated by Django 2.1.1 on 2018-09-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bw3backend', '0004_auto_20180918_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataincoming',
            name='callid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bw3backend.data'),
        ),
    ]
